steps:
  # Configura el entorno
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'project', 'bootcamp-thebridgecloud']

  # Construye la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bootcamp-thebridgecloud/app_uwee', '/uwe/cloud_run']

  # Sube la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bootcamp-thebridgecloud/app_uwee']

  # Implementa la imagen en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        - run
        - deploy
        - mi-servicio-uwee
        - --image=gcr.io/bootcamp-thebridgecloud/app_uwee
        - --region=europe-west1
        - --platform=managed
        - --allow-unauthenticated
        - --port=8080


